apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-demo
  namespace: argocd
spec:
  destination:
    namespace: microservices
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s-manifest
    repoURL: https://github.com/milinddethe15/microservices-demo-aws.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
