pipeline {
    agent any

    parameters {
        choice(
            name: 'ACTION',
            choices: ['apply', 'destroy'],
            description: '🔧 Select the Terraform action to perform'
        )
    }

    stages {
        stage('Checkout from Git') {
            steps {
                echo 'Checking out Git repository...'
            }
        }

        stage('Terraform version') {
            steps {
                sh 'terraform --version'
            }
        }

        stage('Terraform init') {
            steps {
                dir('terraform/platform/eks') {
                    sh 'terraform init --reconfigure'
                }
            }
        }

        stage('Terraform validate') {
            steps {
                dir('terraform/platform/eks') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform plan') {
            steps {
                dir('terraform/platform/eks') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform apply') {
            when {
                expression { params.ACTION == 'apply' }
            }
            steps {
                dir('terraform/platform/eks') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Terraform destroy') {
            when {
                expression { params.ACTION == 'destroy' }
            }
            steps {
                dir('terraform/platform/eks') {
                    sh 'terraform destroy -auto-approve'
                }
            }
        }
    }
}
